### ISSUE TITLE
CUDNN_STATUS_NOT_SUPPORTED 

### ISSUE THREAD

**Issue by godprincelp** [fmassa/object-detection.torch#19]
I tried to run the Examples code from https://github.com/fmassa/object-detection.torch/tree/refactoring. 

It occurs a CUDNN_STATUS_NOT_SUPPORTED error, which is shown as follows:

－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－
In 1 module of nn.Sequential:
In 1 module of nn.ParallelTable:
In 1 module of nn.Sequential:
/scratch2/peng/torch/install/share/lua/5.1/cudnn/init.lua:58: ## Error in CuDNN: CUDNN_STATUS_NOT_SUPPORTED (cudnnSetFilterNdDescriptor)
stack traceback:
    [C]: in function 'error'
    /scratch2/peng/torch/install/share/lua/5.1/cudnn/init.lua:58: in function 'errcheck'
    ...torch/install/share/lua/5.1/cudnn/SpatialConvolution.lua:45: in function 'resetWeightDescriptors'
    ...torch/install/share/lua/5.1/cudnn/SpatialConvolution.lua:358: in function <...torch/install/share/lua/5.1/cudnn/SpatialConvolution.lua:357>
    [C]: in function 'xpcall'
    /scratch2/peng/torch/install/share/lua/5.1/nn/Container.lua:63: in function 'rethrowErrors'
    ...atch2/peng/torch/install/share/lua/5.1/nn/Sequential.lua:44: in function <...atch2/peng/torch/install/share/lua/5.1/nn/Sequential.lua:41>
    [C]: in function 'xpcall'
    /scratch2/peng/torch/install/share/lua/5.1/nn/Container.lua:63: in function 'rethrowErrors'
    ...h2/peng/torch/install/share/lua/5.1/nn/ParallelTable.lua:12: in function <...h2/peng/torch/install/share/lua/5.1/nn/ParallelTable.lua:10>
    [C]: in function 'xpcall'
    /scratch2/peng/torch/install/share/lua/5.1/nn/Container.lua:63: in function 'rethrowErrors'
    ...atch2/peng/torch/install/share/lua/5.1/nn/Sequential.lua:44: in function 'compute'
    ./ImageDetect.lua:16: in function 'detect'
    test_lp.lua:37: in main chunk

WARNING: If you see a stack trace below, it doesn't point to the place where this error occured. Please use only the one above.
stack traceback:
    [C]: at 0x7fa8ac2e54e0
    [C]: in function 'error'
    /scratch2/peng/torch/install/share/lua/5.1/nn/Container.lua:67: in function 'rethrowErrors'
    ...atch2/peng/torch/install/share/lua/5.1/nn/Sequential.lua:44: in function 'compute'
    ./ImageDetect.lua:16: in function 'detect'
    test_lp.lua:37: in main chunk
－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－

**Comment by godprincelp** [comment]
The error comes from the following command:

scores, bboxes = detector:detect(I, bboxes)

**Comment by fmassa** [comment]
Thanks for opening the issue.
The error probably comes from the fact that I saved my example module using CUDNN R2. I'll try to convert it to a newer version and I'll let you know

**Comment by fmassa** [comment]
I didn't manage to reproduce the error on CUDNN R4 either. Are you able to run standard networks using `cudnn` ?

**Comment by godprincelp** [comment]
I updated to CUDNN R4. Now it works well. Thank you.

On Tue, Apr 12, 2016 at 2:32 AM, Francisco Massa notifications@github.com
wrote:

> I didn't manage to reproduce the error on CUDNN R4 either. Are you able to
> run standard networks using cudnn ?
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/fmassa/object-detection.torch/issues/19#issuecomment-208815191

## 

Best Regards,

## Peng Lei

EECS, Oregon State University (OSU)
leip@onid.orst.edu
prcv.plei@gmail.com
1-541-737-7268

**Comment by fmassa** [comment]
cool. closing it then.
